// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto.DAL;

namespace Proyecto.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Proyecto.Models.Tarea", b =>
                {
                    b.Property<int>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Requerimiento")
                        .HasColumnType("TEXT");

                    b.Property<double>("TiempoTotal")
                        .HasColumnType("REAL");

                    b.HasKey("TareaId");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("Proyecto.Models.TareaDetalle", b =>
                {
                    b.Property<int>("TareaDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Requerimiento")
                        .HasColumnType("TEXT");

                    b.Property<int>("TareaId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Tiempo")
                        .HasColumnType("REAL");

                    b.Property<int>("TipoTareaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TareaDetalleId");

                    b.HasIndex("TareaId");

                    b.ToTable("TareaDetalle");
                });

            modelBuilder.Entity("Proyecto.Models.TipoTarea", b =>
                {
                    b.Property<int>("TipoTareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DesTarea")
                        .HasColumnType("TEXT");

                    b.HasKey("TipoTareaId");

                    b.ToTable("TipoTarea");

                    b.HasData(
                        new
                        {
                            TipoTareaId = 1,
                            DesTarea = "Analisis"
                        },
                        new
                        {
                            TipoTareaId = 2,
                            DesTarea = "Diseño"
                        },
                        new
                        {
                            TipoTareaId = 3,
                            DesTarea = "Programación"
                        },
                        new
                        {
                            TipoTareaId = 4,
                            DesTarea = "Prueba"
                        });
                });

            modelBuilder.Entity("Proyecto.Models.TareaDetalle", b =>
                {
                    b.HasOne("Proyecto.Models.Tarea", null)
                        .WithMany("Detalle")
                        .HasForeignKey("TareaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Proyecto.Models.Tarea", b =>
                {
                    b.Navigation("Detalle");
                });
#pragma warning restore 612, 618
        }
    }
}
